/**
 * Word Document Generator using Miyabi AI Agents
 *
 * This module provides functionality to generate Word documents
 * using the docx library, powered by Miyabi framework.
 */

import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { writeFileSync } from 'fs';
import { join } from 'path';

export interface DocumentContent {
  title: string;
  author?: string;
  sections: DocumentSection[];
}

export interface DocumentSection {
  heading: string;
  paragraphs: string[];
}

/**
 * Generate a Word document with the specified content
 * @param content - The document content structure
 * @param outputPath - The path where the Word file should be saved
 * @returns The path to the generated Word file
 */
export async function generateWordDocument(
  content: DocumentContent,
  outputPath?: string
): Promise<string> {
  // Create document sections
  const documentSections: Paragraph[] = [];

  // Add title
  documentSections.push(
    new Paragraph({
      text: content.title,
      heading: HeadingLevel.TITLE,
    })
  );

  // Add author if provided
  if (content.author) {
    documentSections.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Author: ${content.author}`,
            italics: true,
          }),
        ],
      })
    );
  }

  // Add empty line
  documentSections.push(new Paragraph({ text: '' }));

  // Add sections
  for (const section of content.sections) {
    // Add section heading
    documentSections.push(
      new Paragraph({
        text: section.heading,
        heading: HeadingLevel.HEADING_1,
      })
    );

    // Add paragraphs in this section
    for (const paragraphText of section.paragraphs) {
      documentSections.push(
        new Paragraph({
          text: paragraphText,
        })
      );
    }

    // Add spacing between sections
    documentSections.push(new Paragraph({ text: '' }));
  }

  // Create the document
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: documentSections,
      },
    ],
  });

  // Generate buffer
  const buffer = await Packer.toBuffer(doc);

  // Determine output path
  const finalPath = outputPath || join(process.cwd(), 'output.docx');

  // Write file
  writeFileSync(finalPath, buffer);

  console.log(`✓ Word document generated: ${finalPath}`);

  return finalPath;
}

/**
 * Generate a sample Word document demonstrating Miyabi capabilities
 */
export async function generateMiyabiDemoDocument(): Promise<string> {
  const content: DocumentContent = {
    title: 'Miyabi AI Agent System - Demo Document',
    author: 'Miyabi Framework',
    sections: [
      {
        heading: 'Introduction',
        paragraphs: [
          'This document was automatically generated by the Miyabi AI Agent System, demonstrating the integration of AI-powered development tools with document generation capabilities.',
          'Miyabi is an autonomous development framework that leverages 7 specialized AI agents to handle the entire software development lifecycle.',
        ],
      },
      {
        heading: 'Available AI Agents',
        paragraphs: [
          'CoordinatorAgent: Manages task orchestration and parallel execution control using DAG-based task decomposition.',
          'IssueAgent: Analyzes GitHub issues and applies automatic classification using a 53-label system based on organizational design principles.',
          'CodeGenAgent: Generates high-quality TypeScript code using Claude Sonnet 4, fully compliant with strict mode.',
          'ReviewAgent: Performs code quality validation, security scanning, and quality scoring (target: 80+ points).',
          'PRAgent: Automatically creates pull requests following Conventional Commits standards.',
          'DeploymentAgent: Handles CI/CD deployment automation with health checks and automatic rollback capabilities.',
          'TestAgent: Executes automated tests and generates coverage reports (target: 80%+ coverage).',
        ],
      },
      {
        heading: 'Key Features',
        paragraphs: [
          'Autonomous workflow from Issue creation to deployment',
          'Real-time project status monitoring',
          'Parallel task execution for optimal performance',
          'Comprehensive quality assurance with automated testing',
          'Integration with GitHub as an operating system',
        ],
      },
      {
        heading: 'Getting Started',
        paragraphs: [
          'To use Miyabi in your project, simply run: npx miyabi init <project-name>',
          'Create issues to describe tasks, and let the AI agents handle implementation, testing, and deployment.',
          'Monitor progress with: npx miyabi status --watch',
        ],
      },
    ],
  };

  return await generateWordDocument(
    content,
    join(process.cwd(), 'miyabi-demo.docx')
  );
}
